app = "squid-proxy-81efgq"
primary_region = "iad"

[build]

[[services]]
  internal_port = 3128
  protocol = "tcp"

  [[services.ports]]
    port = 3128

[http_service]
  internal_port = 3128
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1