app = "squid-proxy-jiz78g"
primary_region = "iad"

[build]

[[services]]
  internal_port = 3128
  protocol = "tcp"

  [[services.ports]]
    port = 3128

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1